config/routes.rb
Rails.application.routes.draw do
  get 'answer', to: 'coachings#answer'

  get 'ask', to: 'coachings#ask', as: :toto

  get '/', to: 'coachings#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coachings_controller.rb
class CoachingsController < ApplicationController
  def answer
    @query = params[:query]

    if @query.split("").last == "?"
      @answer =  "Silly question, get dressed and go to work!"
    elsif @query == "I am going to work right now!"
      @answer = ""
    else
      @answer = "I don't care, get dressed and go to work!"
    end
  end

  def ask
  end

  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coachings_helper.rb
module CoachingsHelper
end

app/views/coachings/answer.html.erb
<div class="text-center">
  <h1>La réponse à ta question !!</h1>
</div>
<br>
<br>
<br>

<div class="text-center">
  <p>le question est : <%= @query %></p>

  <p>La reponse est: <%= @answer %></p>


  <%= link_to "Repose une question", toto_path %>
</div>

app/views/coachings/ask.html.erb
<div class="text-center">
<h1>Pose ta question</h1>
</div>

<br>
<br>
<br>

<!-- <div class="form-group">
  <form action="/answer" method="GET">
    <input type="text" name="query">
    <button>Submit</button>
  </form>
</div> -->


<div class="container" style="width: 500px">
  <div class="row">
    <div class="col-md-6">
      <form action="/answer" method="GET">
        <div class="form-group">
          <input type="text" class="form-control" name="query">
        </div>
      </div>
      <div class="col-md-6">
       <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </form>
  </div>
</div>

app/views/coachings/home.html.erb
<strong>Salut</strong>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <title>Coaching</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>